-- CREATING SEQUENCE STARTS HERE
CREATE SEQUENCE dept_seq
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
    
CREATE SEQUENCE courses_seq
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

CREATE SEQUENCE books_seq
    MINVALUE 0
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
    
CREATE SEQUENCE books_courses_seq
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
    
CREATE SEQUENCE admin_seq
    MINVALUE 0
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
    
CREATE SEQUENCE user_seq
    MINVALUE 0
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
    
CREATE SEQUENCE uploads_seq
    MINVALUE 0
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
    
CREATE SEQUENCE userCat_seq
    MINVALUE 0
    START WITH 1
    INCREMENT BY 1
    CACHE 10;
    
CREATE SEQUENCE account_seq
    MINVALUE 0
    START WITH 1
    INCREMENT BY 1
    CACHE 10;

-- SEQUENCE ENDS HERE

